"use client";

import { create } from "zustand";

import type {
  BulletCardContent,
  EditorCard,
  HeroCardContent,
  ImageCardContent,
  TextCardContent,
  TwoColumnCardContent,
  CardType,
} from "@/types/cards";

/**
 * Editor store state and actions.
 */
interface EditorState {
  cards: EditorCard[];
  selectedCardId: string | null;
  isGenerating: boolean;
  sidebarCollapsed: boolean;
  setSelectedCard: (id: string | null) => void;
  setCards: (cards: EditorCard[]) => void;
  addCard: (type: CardType) => void;
  updateCard: (id: string, content: EditorCard["content"]) => void;
  deleteCard: (id: string) => void;
  reorderCards: (cards: EditorCard[]) => void;
  toggleSidebar: () => void;
  generateFromPrompt: (prompt: string) => Promise<void>;
}

/**
 * Return a random card id for local-only state keys.
 */
function createId(): string {
  return Math.random().toString(36).slice(2, 11);
}

/**
 * Build starter cards shown on initial load.
 */
function buildMockCards(): EditorCard[] {
  return [
    {
      id: createId(),
      type: "hero",
      content: {
        headline: "Q2 Product Narrative",
        subheading: "A living story, not static slides.",
        cta: "Refine with AI",
      } satisfies HeroCardContent,
    },
    {
      id: createId(),
      type: "text",
      content: {
        title: "Problem",
        body: "Teams spend too long formatting decks instead of clarifying the story.",
      } satisfies TextCardContent,
    },
    {
      id: createId(),
      type: "bullet",
      content: {
        title: "Goals",
        items: [
          "Cut prep time by 60%",
          "Keep visual voice consistent",
          "Enable instant revisions",
        ],
      } satisfies BulletCardContent,
    },
    {
      id: createId(),
      type: "twoColumn",
      content: {
        leftTitle: "Before",
        leftBody: "Manual edits, duplicate files, fragmented feedback.",
        rightTitle: "After",
        rightBody: "One adaptive document with collaborative AI support.",
      } satisfies TwoColumnCardContent,
    },
  ];
}

/**
 * Build an empty card template based on card type.
 */
function buildCard(type: CardType): EditorCard {
  if (type === "hero") {
    return {
      id: createId(),
      type,
      content: {
        headline: "New Hero Title",
        subheading: "Add a strong one-line narrative.",
        cta: "Get Started",
      } satisfies HeroCardContent,
    };
  }

  if (type === "image") {
    return {
      id: createId(),
      type,
      content: {
        title: "Image Block",
        imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1400&q=80",
        caption: "Replace with your own visual context.",
      } satisfies ImageCardContent,
    };
  }

  if (type === "bullet") {
    return {
      id: createId(),
      type,
      content: {
        title: "Bullet Block",
        items: ["Point one", "Point two", "Point three"],
      } satisfies BulletCardContent,
    };
  }

  if (type === "twoColumn") {
    return {
      id: createId(),
      type,
      content: {
        leftTitle: "Left",
        leftBody: "Add left-side detail.",
        rightTitle: "Right",
        rightBody: "Add right-side detail.",
      } satisfies TwoColumnCardContent,
    };
  }

  return {
    id: createId(),
    type,
    content: {
      title: "Text Block",
      body: "Type your content here...",
    } satisfies TextCardContent,
  };
}

/**
 * Convert AI prompt text into a deterministic set of cards.
 */
function buildGeneratedCards(prompt: string): EditorCard[] {
  const cleaned = prompt.trim() || "Untitled Story";
  return [
    {
      id: createId(),
      type: "hero",
      content: {
        headline: cleaned,
        subheading: "Generated by your AI copilot.",
        cta: "Continue",
      } satisfies HeroCardContent,
    },
    {
      id: createId(),
      type: "text",
      content: {
        title: "Context",
        body: `This section frames ${cleaned.toLowerCase()} for stakeholders with concise narrative and intent.`,
      } satisfies TextCardContent,
    },
    {
      id: createId(),
      type: "bullet",
      content: {
        title: "Key Points",
        items: [
          "Define the core objective",
          "Highlight market or user impact",
          "Present measurable next steps",
        ],
      } satisfies BulletCardContent,
    },
    {
      id: createId(),
      type: "twoColumn",
      content: {
        leftTitle: "Opportunities",
        leftBody: "Capture growth vectors and strategic upside.",
        rightTitle: "Risks",
        rightBody: "Outline constraints with mitigation plans.",
      } satisfies TwoColumnCardContent,
    },
  ];
}

/**
 * Centralized editor state for cards, selection, and generation lifecycle.
 */
export const useEditorStore = create<EditorState>((set) => ({
  cards: buildMockCards(),
  selectedCardId: null,
  isGenerating: false,
  sidebarCollapsed: false,
  setSelectedCard: (id) => set({ selectedCardId: id }),
  setCards: (cards) => set({ cards }),
  addCard: (type) =>
    set((state) => {
      const card = buildCard(type);
      return {
        cards: [...state.cards, card],
        selectedCardId: card.id,
      };
    }),
  updateCard: (id, content) =>
    set((state) => ({
      cards: state.cards.map((card) =>
        card.id === id
          ? {
              ...card,
              content,
            }
          : card,
      ),
    })),
  deleteCard: (id) =>
    set((state) => ({
      cards: state.cards.filter((card) => card.id !== id),
      selectedCardId: state.selectedCardId === id ? null : state.selectedCardId,
    })),
  reorderCards: (cards) => set({ cards }),
  toggleSidebar: () =>
    set((state) => ({
      sidebarCollapsed: !state.sidebarCollapsed,
    })),
  generateFromPrompt: async (prompt) => {
    set({ isGenerating: true });
    await new Promise((resolve) => setTimeout(resolve, 1400));
    set({
      cards: buildGeneratedCards(prompt),
      selectedCardId: null,
      isGenerating: false,
    });
  },
}));
